title: Boston AI in Medicine
email: contact@aim.boston
description: >-
  Open Medical Data is part of Boston AI in Medicine.
baseurl: "/medical-data" # the subpath of your site
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BostonAIM
github_username:  boston-aim

permalink: none

sass:
  style: compressed
